apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-prod
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: /tmp/prod-postgres-data
