name: Deploy Infra to GKE

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Apply Infra K8s Resources
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate with GKE
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_ZONE }}
        project_id: ${{ secrets.GKE_PROJECT }}


    - name: Apply All K8s Resources
      run: |
        kubectl apply -f k8s/
